/** Featured films (film unggulan): prioritised on homepage and Film Terpopuler. */
export const FEATURED_TITLE_PRIORITY = [
  "Demon Slayer",
  "365 days",
  "beautiful disaster",
  "love lesson",
  "Spartacus",
  "Purpose of reunion",
  "School of rock",
  "Avatar 2009",
  "How to train your dragon",
  "Geostorm",
  "The Dreamers",
  "Fast and Furious 5",
  "The Polar Express",
  "Avatar: Fire and Ash",
  "Zootopia 2",
  "Avatar: The Way of Water",
  "Avatar",
  "Now You See Me: Now You Don't",
  "Bu feng shui ying",
  "Predator: Badlands",
  "The Rip",
  "Greenland 2: Migration",
  "Der Tiger (The Tank)",
  "The SpongeBob Movie",
  "Anaconda",
  "Jurassic World: Rebirth",
  "Baahubali: The Epic",
  "Sisu 2",
  "Mission: Impossible - The Final Reckoning",
  "Banduan",
  "Greenland",
  "The Great Flood",
  "Superman",
  "Avengers",
  "Wicked: For Good",
];

